import Link from "next/link";
import { ArrowRight, Clock, ChevronLeft } from "lucide-react";

export default function AlgorithmicMalpracticeArticle() {
  const comparisonRows = [
    { dimension: "Nature", cyber: "Episodic and adversarial", ai: "Continuous and endogenous" },
    { dimension: "Origin", cyber: "External threat actors", ai: "Internal system failures" },
    { dimension: "Frequency", cyber: "Discrete events", ai: "Scales with usage volume" },
    { dimension: "Detection", cyber: "Often rapid — breach alerts", ai: "Can propagate silently" },
    { dimension: "Accumulation", cyber: "Infrastructure / cloud outages", ai: "Shared models and providers" },
    { dimension: "Liability", cyber: "Data protection, GDPR", ai: "Advice, decisions, outputs" },
    { dimension: "Exposure unit", cyber: "Revenue, records, devices", ai: "Model queries, decisions made" },
  ];

  const autonomyLevels = [
    { label: "Read-only / advisory", pct: 15, risk: "Low", riskColor: "#3B6D11", riskBg: "rgba(59,109,17,0.15)", note: "Provides information or recommendations only — human makes final decision" },
    { label: "Write access / code generation", pct: 55, risk: "Medium–High", riskColor: "#854F0B", riskBg: "rgba(133,79,11,0.15)", note: "Can modify files, generate and deploy code, or alter system configurations" },
    { label: "Execution / transaction authority", pct: 85, risk: "Very High", riskColor: "#E63946", riskBg: "rgba(230,57,70,0.15)", note: "Can execute trades, bind contracts, make financial commitments autonomously" },
    { label: "Full agentic autonomy", pct: 100, risk: "Extreme", riskColor: "#E63946", riskBg: "rgba(230,57,70,0.15)", note: "Multi-step autonomous action with minimal human oversight or intervention" },
  ];

  const incidents = [
    { company: "McKinsey — indirect prompt injection", body: "An internal AI system was compromised through malicious instructions embedded in documents the AI was asked to summarise. Sensitive data was exfiltrated. The failure was not in the perimeter — it was in the AI decision layer itself." },
    { company: "Amazon — hallucinated security vulnerabilities", body: "AI-generated code introduced subtle backdoor vulnerabilities into AWS internal tools. The failures were logically coherent but architecturally insecure — invisible to standard automated scanners. Driven by output quotas, engineers had begun rubber-stamping AI outputs." },
    { company: "Air Canada — legal liability for AI hallucinations", body: "A tribunal ruling established that organisations are legally responsible for incorrect outputs generated by their AI systems. If your chatbot promises coverage that does not exist, your E&O exposure is absolute. This precedent has material implications for every carrier deploying AI in customer-facing roles." },
  ];

  const lossCategories = [
    { num: "01", color: "#3B6D11", title: "Isolated errors", body: "Individual incorrect outputs or decisions affecting a single transaction or customer interaction. Highest frequency, lowest severity. Similar in profile to standard professional indemnity claims." },
    { num: "02", color: "#854F0B", title: "Embedded failures", body: "Errors incorporated into operational workflows or automated rules, affecting multiple outcomes before detection. The most dangerous category — a single defect can propagate across thousands of transactions silently." },
    { num: "03", color: "#E63946", title: "Systemic events", body: "Failures that trigger regulatory, legal, or reputational consequences across an organisation or sector. Lowest frequency, catastrophic severity. Potentially correlated across multiple insureds using the same underlying model." },
  ];

  const accumulationDimensions = [
    { label: "Underlying model or provider", body: "Which foundation model powers the system? OpenAI, Google, Anthropic, open-source? Correlated exposure across insureds using the same provider." },
    { label: "Application architecture", body: "Is the AI embedded in core processes or peripheral tasks? RAG system or fine-tuned model? Architecture determines propagation risk." },
    { label: "Use-case criticality", body: "Is the AI making financial, legal, or medical decisions? Or supporting lower-stakes workflows? Criticality determines severity potential." },
  ];

  const uwRequirements = [
    { num: "01", title: "AI Bill of Materials (AIBOM)", body: "Full visibility over every model and dependency used by the insured — including third-party APIs, fine-tuned models, and retrieval layers. Without this, underwriters are pricing a black box." },
    { num: "02", title: "Human-in-the-loop for critical decisions", body: "Mandatory human oversight for financial, legal, or customer-facing commitments. The Air Canada ruling makes clear that this is not optional — it is the line between insurable and uninsurable." },
    { num: "03", title: "Input validation and prompt controls", body: "AI systems must treat all external inputs as potentially untrusted data — scrubbed and validated before processing. The McKinsey incident demonstrates exactly what happens when they do not." },
    { num: "04", title: "Ongoing monitoring and update obligations", body: "Static policy controls are insufficient. AI systems evolve. Policy structures must incorporate obligations to maintain, monitor, and update safeguards over time — not just at inception." },
  ];

  const conclusions = [
    { num: "01", title: "Redefine exposure", body: "AI risk scales with activity, not organisational size. Move from revenue-based exposure units to interaction volume, decision frequency, and autonomy level. The underwriting question is not how big is this company — but how many AI decisions does it make per day." },
    { num: "02", title: "System design drives loss", body: "Architecture, controls, and autonomy level are central to the risk profile. Without visibility into these elements — through pre-bind technical assessments and AIBOM requirements — pricing will be structurally imprecise. Carriers that invest in this capability will select and price better." },
    { num: "03", title: "Correlation is the critical unknown", body: "Shared models and infrastructure introduce a new form of accumulation risk that is not yet fully understood but is likely to be material. Carriers need to track underlying model exposure across their portfolios — not just insured names — before this risk crystallises at scale." },
  ];

  return (
    <div className="bg-[#0a0a0a] min-h-screen">
      <section className="relative pt-40 pb-16 px-6 overflow-hidden">
        <div className="absolute top-0 left-[20%] w-[500px] h-[500px] rounded-full blur-[160px] opacity-10" style={{ background: "radial-gradient(circle, rgba(230,57,70,0.7) 0%, transparent 70%)" }} />
        <div className="max-w-3xl mx-auto">
          <Link href="/insights" className="inline-flex items-center gap-2 text-white/40 hover:text-white transition-colors text-sm mb-10">
            <ChevronLeft size={14} />
            Back to Insights
          </Link>
          <div className="flex items-center gap-4 mb-6">
            <span className="mono-label text-[9px] px-3 py-1 rounded-full bg-[#E63946]/15 text-[#E63946]">AI Risk · Insurance</span>
            <span className="mono-label text-white/20 text-[9px]">March 2026</span>
            <div className="flex items-center gap-2 text-white/20">
              <Clock size={11} />
              <span className="mono-label text-[9px]">6 min read</span>
            </div>
          </div>
          <h1 className="font-display text-white text-4xl md:text-5xl leading-tight mb-8">
            From Cyber Liability to Algorithmic Malpractice: How Insurers Can Underwrite AI Risk in 2026
          </h1>
          <p className="text-white/50 text-xl leading-relaxed border-l-2 border-[#E63946] pl-5">
            The insurance industry spent two decades building a playbook for cyber risk. That playbook is now being challenged by AI. The shift is not gradual — it is structural.
          </p>
        </div>
      </section>

      <div className="divider-gradient" />

      <article className="py-16 px-6">
        <div className="max-w-3xl mx-auto space-y-8 text-white/70 text-base leading-relaxed">

          <p>The insurance industry has a well-established framework for cyber risk: adversarial intrusion, data breach, ransomware, business interruption. Underwriters know the exposure units, the severity distributions, and the accumulation dynamics. That framework, built painstakingly over twenty years, is now being challenged by a fundamentally different risk class.</p>
          <p>Artificial intelligence risk — what we term Algorithmic Malpractice — does not behave like cyber risk. It is not episodic and adversarial. It is continuous and endogenous. Understanding that distinction is the starting point for every insurer navigating this transition.</p>

          <h2 className="font-display text-white text-2xl mt-10 mb-6">The incidents that changed the market</h2>
          <div className="space-y-4">
            {incidents.map((inc) => (
              <div key={inc.company} className="pl-5 py-1" style={{ borderLeft: "3px solid #E63946" }}>
                <p className="font-display text-white text-base mb-2">{inc.company}</p>
                <p className="text-white/50 text-sm leading-relaxed">{inc.body}</p>
              </div>
            ))}
          </div>

          <div className="border-t border-b border-white/10 py-8 my-10">
            <p className="font-display text-white text-xl italic leading-relaxed">"The primary risk is no longer external intrusion. It is failure within the AI decision layer itself."</p>
          </div>

          <h2 className="font-display text-white text-2xl mt-10 mb-6">Cyber risk vs AI risk — a structural comparison</h2>
          <p>These are not two versions of the same problem. They require different underwriting frameworks, different exposure units, and different accumulation models.</p>

          <div className="glass rounded-2xl overflow-hidden my-8">
            <div className="grid grid-cols-3 gap-4 px-6 py-3 border-b border-white/10">
              <p className="mono-label text-white/30 text-[9px]">Dimension</p>
              <p className="mono-label text-white/30 text-[9px]">Cyber risk</p>
              <p className="mono-label text-[#E63946] text-[9px]">AI / algorithmic risk</p>
            </div>
            {comparisonRows.map((row, i) => (
              <div
                key={row.dimension}
                className="grid grid-cols-3 gap-4 px-6 py-4 border-b border-white/5 last:border-0"
                style={{ background: i % 2 === 0 ? "rgba(255,255,255,0.02)" : "transparent" }}
              >
                <p className="text-white/60 text-sm font-medium">{row.dimension}</p>
                <p className="text-white/40 text-sm">{row.cyber}</p>
                <p className="text-sm font-medium" style={{ color: "#E63946CC" }}>{row.ai}</p>
              </div>
            ))}
          </div>

          <h2 className="font-display text-white text-2xl mt-10 mb-4">Rethinking exposure: activity-based underwriting</h2>
          <p>Traditional insurance metrics — revenue, employees, locations — are poor proxies for AI risk. Exposure is more closely linked to interaction volume: the number of model queries, automated decisions, and customer-facing outputs generated by the system.</p>
          <p>This reflects a key mathematical property of AI systems. If the probability of a material failure per interaction is even a fraction of a percent, the probability of at least one failure across millions of interactions approaches certainty. Risk scales with usage, not with the size of the organisation.</p>

          <div className="glass rounded-xl p-6 my-6">
            <p className="mono-label text-[#E63946] text-[9px] mb-3">Probability of failure formula</p>
            <p className="font-mono text-white text-lg mb-3">Pf = 1 − (1 − Pe)ⁿ</p>
            <p className="text-white/40 text-sm leading-relaxed">Where Pe = per-interaction error probability and n = number of interactions. At Pe = 0.0001% and n = 10,000,000 interactions per year, Pf approaches 1.0 — mathematical certainty of at least one major incident annually.</p>
          </div>

          <h2 className="font-display text-white text-2xl mt-10 mb-6">Three loss categories insurers must price</h2>
          <div className="space-y-4 my-6">
            {lossCategories.map((lc) => (
              <div key={lc.num} className="glass rounded-xl p-6 flex gap-5">
                <span className="font-mono text-2xl font-bold flex-shrink-0" style={{ color: `${lc.color}60` }}>{lc.num}</span>
                <div>
                  <p className="font-display text-white text-lg mb-2">{lc.title}</p>
                  <p className="text-white/50 text-sm leading-relaxed">{lc.body}</p>
                </div>
              </div>
            ))}
          </div>

          <h2 className="font-display text-white text-2xl mt-10 mb-4">Autonomy level drives risk loading</h2>
          <p>One of the clearest emerging insights in AI underwriting is that risk varies significantly with the level of autonomy granted to the AI system. The greater the system's ability to act independently, the greater the potential for errors to translate directly into financial loss.</p>

          <div className="glass rounded-2xl p-6 my-8 space-y-6">
            {autonomyLevels.map((level) => (
              <div key={level.label}>
                <div className="flex justify-between items-start mb-1">
                  <p className="text-white/80 text-sm font-medium">{level.label}</p>
                  <span
                    className="mono-label text-[9px] px-3 py-1 rounded-full flex-shrink-0 ml-4"
                    style={{ color: level.riskColor, background: level.riskBg }}
                  >
                    {level.risk}
                  </span>
                </div>
                <p className="text-white/30 text-xs mb-2">{level.note}</p>
                <div className="h-2 bg-white/5 rounded-full overflow-hidden">
                  <div className="h-full rounded-full" style={{ width: `${level.pct}%`, background: level.riskColor }} />
                </div>
              </div>
            ))}
          </div>

          <h2 className="font-display text-white text-2xl mt-10 mb-4">Accumulation: the balance sheet risk nobody is pricing yet</h2>
          <p>The most significant challenge for insurers is accumulation risk. A relatively small number of AI providers — OpenAI, Google, Anthropic, Microsoft — underpin the vast majority of enterprise AI deployments. This creates correlated exposure that does not exist in cyber in the same form.</p>
          <p>A model update, a discovered vulnerability, or a systemic error in decision-making logic at one of these providers could simultaneously affect thousands of insureds. Unlike a cloud outage, this form of accumulation may be invisible until losses begin to crystallise.</p>

          <p className="text-white/60 text-sm font-medium mt-6 mb-3">Insurers need to track accumulation across three dimensions:</p>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 my-6">
            {accumulationDimensions.map((dim) => (
              <div key={dim.label} className="glass rounded-xl p-5">
                <p className="font-display text-white text-base mb-2">{dim.label}</p>
                <p className="text-white/40 text-sm leading-relaxed">{dim.body}</p>
              </div>
            ))}
          </div>

          <h2 className="font-display text-white text-2xl mt-10 mb-6">Underwriting through product design</h2>
          <p>In AI risk, underwriting cannot rely solely on risk selection and pricing. It must be reinforced through policy design and enforceable controls. Four elements are becoming non-negotiable.</p>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-5 my-8">
            {uwRequirements.map((req) => (
              <div key={req.num} className="glass rounded-2xl p-6" style={{ borderTop: "3px solid #E63946" }}>
                <p className="mono-label text-[#E63946] text-[9px] mb-3">Requirement {req.num}</p>
                <p className="font-display text-white text-lg mb-3">{req.title}</p>
                <p className="text-white/50 text-sm leading-relaxed">{req.body}</p>
              </div>
            ))}
          </div>

          <div className="divider-gradient my-10" />

          <h2 className="font-display text-white text-2xl mt-10 mb-6">Three conclusions for insurers</h2>
          <div className="space-y-4">
            {conclusions.map((c) => (
              <div key={c.num} className="glass rounded-xl p-6 flex gap-5">
                <span className="font-mono text-[#E63946]/40 text-2xl font-bold flex-shrink-0">{c.num}</span>
                <div>
                  <p className="font-display text-white text-lg mb-2">{c.title}</p>
                  <p className="text-white/50 text-sm leading-relaxed">{c.body}</p>
                </div>
              </div>
            ))}
          </div>

          <div className="glass rounded-xl p-8 mt-10">
            <p className="mono-label text-[#E63946] text-[9px] mb-4">Summary</p>
            <p className="text-white/70 leading-relaxed">The transition from cyber liability to algorithmic malpractice is not a gradual evolution. It is a structural shift in how operational risk manifests in a digital economy. AI risk cannot be treated as an extension of cyber. It requires its own underwriting discipline, grounded in technical understanding, structured data, and explicit control of accumulation. Those who build that capability early will be better positioned to navigate what is likely to become a defining liability class of the next decade.</p>
          </div>

          <p className="text-white/30 text-xs mt-10 leading-relaxed">Eudaimon Consulting, March 2026. For general information purposes only. Eudaimon Consulting makes no representations or warranties of any kind about the completeness or accuracy of this article. Any reliance placed on this information is strictly at your own risk.</p>
        </div>
      </article>

      <section className="py-24 px-6 bg-[#080808]">
        <div className="max-w-3xl mx-auto">
          <div className="divider-gradient mb-16" />
          <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-6">
            <div>
              <p className="mono-label text-white/30 text-[9px] mb-2">Want to discuss your AI risk strategy?</p>
              <p className="font-display text-white text-2xl">Talk to Eudaimon Consulting.</p>
            </div>
            <Link href="/contact" className="group flex items-center gap-2 px-7 py-3.5 bg-[#E63946] text-white rounded-full font-medium hover:bg-[#c92a35] transition-all flex-shrink-0">
              Get in Touch
              <ArrowRight size={16} className="group-hover:translate-x-1 transition-transform" />
            </Link>
          </div>
        </div>
      </section>
    </div>
  );
}
